### ISSUE TITLE
看了你的仓库描述

### ISSUE THREAD

**Issue by paoludecaic** [QLozin/ManiaciaChao-hustzc#1]
看了你的仓库描述，就是说，有没有一个可能，我是先在Gitee上看到了，github上是后看到的

**Comment by QLozin** [comment]
> 看了你的仓库描述，就是说，有没有一个可能，我是先在Gitee上看到了，github上是后看到的

很高兴你能在这里看到，但是Gitee的下载需要实名认证，而不喜欢实名认证的程序员就会来到GitHub找找镜像 :)

**Comment by paoludecaic** [comment]
> > 看了一下你的仓库描述，就是说，有没有一个可能，我是先在Gitee上看到的，github上是后看到的
> 
> 很高兴你能在这里看到，但是Gitee的下载需要实名认证，而不喜欢实名认证的程序员可以来这里找GitHub镜像:)

这样啊
